import test from 'node:test';
import assert from 'node:assert/strict';
import {CATALOG,QUESTIONS} from '../dist/catalog.js';
import * as E from '../dist/engine.js';
import * as V1 from '../dist/engine-v1.js';
const add=(s,id,n=1,modules=[])=>{for(let i=0;i<n;i++)s=E.addUnit(s,id,{modules});return s;};
const ready=s=>{s=E.copy(s);s.draft.name='Test';for(const [k]of QUESTIONS)s.draft.rationale[k]='Begründung';return s;};
function reference(){let s=E.fresh();for(const [id,n]of [['network',1],['airbase',1],['frigate',8],['corvette',5],['submarine',6],['mine',10],['supply',3],['intelligence',3],['tender',6],['tanker',2],['helicopter',18]])s=add(s,id,n);s=add(s,'frigate',3,['air']);s=add(s,'helicopter',22,['asw']);return add(s,'plane',2,['asw']);}
test('Neue Referenz und zusätzliche Korvette passen',()=>{const s=reference();assert.deepEqual(E.totals(s.draft.units),{build:703,operation:356.5,personnel:323});assert.deepEqual(E.totals(add(s,'corvette').draft.units),{build:713,operation:361.5,personnel:328});assert.deepEqual(E.submissionErrors(ready(s).draft),[]);});
test('Trägerentwurf unverändert',()=>{let s=E.fresh();for(const [id,n]of [['airbase',1],['network',1],['carrier',1],['airwing',1],['frigate',2],['supply',2]])s=add(s,id,n);s=add(s,'frigate',1,['air']);assert.deepEqual(E.totals(s.draft.units),{build:564,operation:262,personnel:253});});
test('Alle Preise sind ganzzahlige Viertelpunkte, Module ohne Personal',()=>{for(const c of CATALOG){for(const p of [c.cost,...Object.values(c.moduleCosts)])for(const n of Object.values(p))assert.ok(Number.isSafeInteger(n)&&n>=0);for(const p of Object.values(c.moduleCosts))assert.equal(p.personnel,0);}});
test('Plätze, Typen, Wiederholung und Führungsnetz werden geprüft',()=>{let s=add(E.fresh(),'frigate');const id=s.draft.units[0].id;assert.throws(()=>E.setModules(s,id,['strike']),/Datennetz/);assert.throws(()=>E.setModules(s,id,['air','air']),/Spezialisierungen/);assert.throws(()=>E.setModules(s,id,['air','asw','surface']),/Spezialisierungen/);assert.throws(()=>add(E.fresh(),'corvette',1,['air']),/nicht erlaubt/);s=add(s,'network');s=E.setModules(s,id,['strike','asw']);assert.equal(E.totals(s.draft.units).personnel,15);assert.throws(()=>E.removeUnit(s,s.draft.units[1].id),/abhängige/);s=E.setModules(s,id,[]);assert.deepEqual(E.unitCost(s.draft.units[0]),{build:20,operation:10,personnel:10});});
test('Luftfahrzeuge einzeln und kompatible Spezialisierungen',()=>{let s=add(add(E.fresh(),'airbase'),'network');s=add(s,'helicopter',1,['asw','surface']);assert.deepEqual(E.unitCost(s.draft.units.at(-1)),{build:5,operation:3,personnel:1});assert.throws(()=>add(s,'fixedDrone',1,['asw']),/nicht erlaubt/);assert.throws(()=>add(s,'rotorDrone',1,['asw','surface']),/Spezialisierungen/);assert.throws(()=>add(E.fresh(),'plane'),/Marinefliegerbasis/);});
test('Einschiffungskapazitäten und Drohnen separat',()=>{for(const [host,n]of [['frigate',2],['cruiser',2],['supply',6],['amphibiousCarrier',12]]){let s=add(add(add(E.fresh(),'airbase'),'network'),host);const id=s.draft.units.at(-1).id;for(let i=0;i<n;i++)s=E.addUnit(s,'helicopter',{parentId:id});assert.throws(()=>E.addUnit(s,'helicopter',{parentId:id}),/voll belegte/);s=E.addUnit(s,'rotorDrone',{parentId:id});assert.throws(()=>E.addUnit(s,'rotorDrone',{parentId:id}),/voll belegte/);assert.equal(E.issues(s.draft.units).length,0);}});
test('Marineinfanterie an Land, atomare Einschiffung und Logistikfreigabe',()=>{let s=add(E.fresh(),'marines',2);const m=s.draft.units[0].id;assert.equal(E.issues(s.draft.units).length,0);s=add(add(s,'dock',2),'logistics');const docks=s.draft.units.filter(u=>u.type==='dock'),log=s.draft.units.at(-1).id;assert.throws(()=>E.assignUnit(s,m,docks[0].id,null),/Logistik/);s=E.assignUnit(s,m,docks[0].id,log);assert.throws(()=>E.assignUnit(s,s.draft.units[1].id,docks[1].id,log),/nur ein/);assert.throws(()=>E.removeUnit(s,log),/abhängige/);s=E.assignUnit(s,m,null,log);assert.equal(s.draft.units[0].supportId,null);assert.ok(s.draft.units.some(u=>u.id===log));});
test('Konfigurationen gruppieren und Identität erhalten',()=>{let s=add(E.fresh(),'frigate',2,['asw','air']);s=add(s,'frigate');assert.deepEqual(E.groupUnits(s.draft.units).map(g=>g.length),[2,1]);const id=s.draft.units[0].id;s=E.setModules(s,id,['surface']);assert.equal(s.draft.units[0].id,id);assert.equal(E.groupUnits(s.draft.units).length,3);});
function oldFleet(){let s=V1.fresh();for(const [id,n]of [['network',1],['airbase',1],['frigate',8],['airdefense',3],['corvette',5],['submarine',6],['mine',10],['supply',3],['intelligence',3],['tender',6],['tanker',2],['helicopter',11],['transport',3],['patrol',1]])for(let i=0;i<n;i++)s=V1.addUnit(s,id);return s;}
test('Alte Referenz wird korrekt aufgelöst',()=>{const s=E.parseDocument(oldFleet());assert.deepEqual(E.totals(s.draft.units),{build:703,operation:356.5,personnel:323});assert.equal(s.draft.units.filter(u=>u.type==='helicopter').length,40);assert.deepEqual(E.parseDocument(JSON.parse(JSON.stringify(s))),s);});
test('Alte Abgabe bleibt unverändert und wird erst zur Überarbeitung umgerechnet',()=>{const old=V1.submit(ready(oldFleet()));const s=E.parseDocument(old);assert.deepEqual(E.totals(s.draft.units,s.draft.catalogVersion),{build:697,operation:355,personnel:325});assert.deepEqual(s.submissions[0].units,old.submissions[0].units);const next=E.revise(s);assert.deepEqual(E.totals(next.draft.units),{build:703,operation:356.5,personnel:323});assert.deepEqual(next.submissions,s.submissions);assert.deepEqual(E.parseDocument(JSON.parse(JSON.stringify(next))),next);});
test('Migration erhält Zuordnungen und löst Effektoren auf',()=>{let s=V1.fresh();for(const id of ['network','airbase','airdefense','effectors','helicopter','supply','transport','dock','logistics','marines','drone'])s=V1.addUnit(s,id);const f=s.draft.units.find(u=>u.type==='airdefense'),h=s.draft.units.find(u=>u.type==='helicopter'),t=s.draft.units.find(u=>u.type==='transport');s=V1.assignUnit(s,h.id,f.id,null);s=V1.assignUnit(s,t.id,s.draft.units.find(u=>u.type==='supply').id,null);const next=E.parseDocument(s);assert.deepEqual(next.draft.units.find(u=>u.id===f.id).modules,['air','strike']);assert.equal(next.draft.units.filter(u=>u.parentId===f.id).length,2);assert.equal(next.draft.units.filter(u=>u.type==='effectors').length,0);assert.equal(E.issues(next.draft.units).length,0);});
test('Mengengrenze bricht Migration ohne Mutation ab',()=>{let s=V1.fresh();s=V1.addUnit(s,'airbase');for(let i=0;i<167;i++)s=V1.addUnit(s,'transport');const before=JSON.stringify(s);assert.throws(()=>E.parseDocument(s),/1.000/);assert.equal(JSON.stringify(s),before);});
test('Abgabe, Revision und Dateirundreise',()=>{let s=E.submit(ready(add(E.fresh(),'corvette',1,['surface'])));assert.throws(()=>add(s,'frigate'),/abgegeben/);s=E.revise(s);s=add(s,'marines');s=E.submit(s);assert.deepEqual(E.parseDocument(JSON.parse(JSON.stringify(s))),s);const bad=E.copy(s);bad.draft.name='Geändert';assert.throws(()=>E.parseDocument(bad),/nachträglich/);});
test('Import lässt keine fremden Preise, Module oder Karten zu',()=>{const s=add(E.fresh(),'corvette');for(const type of ['evil','__proto__','constructor']){const bad=E.copy(s);bad.draft.units[0].type=type;assert.throws(()=>E.parseDocument(bad),/Ungültige Einheit/);}const bad=E.copy(s);bad.draft.units[0].modules=['__proto__'];assert.throws(()=>E.parseDocument(bad),/nicht erlaubt/);s.draft.units[0].cost={build:-100};assert.equal(E.parseDocument(s).draft.units[0].cost,undefined);});
test('Überbudget bleibt Entwurf, vollständige Begründungen Pflicht',()=>{assert.throws(()=>E.submit(ready(add(E.fresh(),'frigate',40))),/überschritten/);assert.equal(E.submissionErrors(add(E.fresh(),'corvette').draft).length,5);});
