import test from 'node:test';
import assert from 'node:assert/strict';
import {CATALOG,LIMITS,QUESTIONS} from '../dist/catalog-v1.js';
import {fresh,copy,totals,addUnit,removeUnit,assignUnit,freeHosts,freeSupports,issues,submit,revise,parseDocument,submissionErrors} from '../dist/engine-v1.js';
function add(s,type,n=1){for(let i=0;i<n;i++)s=addUnit(s,type);return s;}
function ready(s){s=copy(s);s.draft.name='Testgruppe';for(const [key] of QUESTIONS)s.draft.rationale[key]='Begründete Entscheidung für '+key;return s;}
test('24 eindeutige Karten mit gültigen Ressourcen',()=>{assert.equal(CATALOG.length,24);assert.equal(new Set(CATALOG.map(c=>c.id)).size,24);for(const c of CATALOG)for(const v of Object.values(c.cost))assert.ok(Number.isSafeInteger(v)&&v>=0);});
test('Referenzflotte 697 / 355 / 325 und zusätzliche Korvette passen',()=>{let s=fresh();for(const [id,n]of [['network',1],['airbase',1],['frigate',8],['airdefense',3],['corvette',5],['submarine',6],['mine',10],['supply',3],['intelligence',3],['tender',6],['tanker',2],['helicopter',11],['transport',3],['patrol',1]])s=add(s,id,n);assert.deepEqual(totals(s.draft.units),{build:697,operation:355,personnel:325});assert.equal(issues(s.draft.units).length,0);s=add(s,'corvette');assert.deepEqual(totals(s.draft.units),{build:707,operation:360,personnel:330});assert.equal(submissionErrors(ready(s).draft).length,0);});
test('Trägerentwurf 564 / 262 / 253',()=>{let s=fresh();for(const [id,n]of [['airbase',1],['network',1],['carrier',1],['airwing',1],['frigate',2],['airdefense',1],['supply',2]])s=add(s,id,n);assert.deepEqual(totals(s.draft.units),{build:564,operation:262,personnel:253});assert.equal(submissionErrors(ready(s).draft).length,0);});
test('Voraussetzungen verhindern Hinzufügen und Entfernen',()=>{const s=fresh();assert.throws(()=>add(s,'carrier'),/Marinefliegerbasis/);assert.equal(s.draft.units.length,0);let next=add(add(s,'airbase'),'patrol');assert.throws(()=>removeUnit(next,next.draft.units[0].id),/abhängige/);assert.throws(()=>add(next,'airbase'),/Bereits/);next=removeUnit(next,next.draft.units[1].id);next=removeUnit(next,next.draft.units[0].id);assert.deepEqual(totals(next.draft.units),{build:0,operation:0,personnel:0});});
test('Hostplätze sind je Pakettyp exklusiv und erlauben Umordnen',()=>{let s=add(add(add(fresh(),'airbase'),'network'),'frigate',2);s=add(s,'helicopter',2);s=add(s,'effectors',2);const frigates=s.draft.units.filter(u=>u.type==='frigate'),helicopters=s.draft.units.filter(u=>u.type==='helicopter'),eff=s.draft.units.filter(u=>u.type==='effectors');s=assignUnit(s,helicopters[0].id,frigates[0].id,null);assert.throws(()=>assignUnit(s,helicopters[1].id,frigates[0].id,null),/bereits/);s=assignUnit(s,helicopters[0].id,frigates[1].id,null);s=assignUnit(s,helicopters[1].id,frigates[0].id,null);assert.equal(freeHosts(s.draft.units,'helicopter').length,0);assert.throws(()=>add(s,'effectors'),/freie Plattform/);assert.notEqual(eff[0].parentId,eff[1].parentId);s=assignUnit(s,helicopters[0].id,null,null);assert.equal(freeHosts(s.draft.units,'helicopter').length,1);});
test('Marineinfanterie benötigt eigene Logistik und eigene Plattformkapazität',()=>{let s=add(fresh(),'dock',2);assert.throws(()=>add(s,'marines'),/Logistik/);s=add(add(s,'logistics'),'marines');assert.equal(freeSupports(s.draft.units,'marines').length,0);assert.throws(()=>add(s,'marines'),/Logistik/);s=add(add(s,'logistics'),'marines');const m=s.draft.units.filter(u=>u.type==='marines');assert.notEqual(m[0].supportId,m[1].supportId);assert.throws(()=>assignUnit(s,m[1].id,m[1].parentId,m[0].supportId),/nur ein Kräftepaket/);assert.throws(()=>removeUnit(s,m[0].supportId),/abhängige/);assert.equal(issues(s.draft.units).length,0);});
test('Träger benötigt Luftgruppe nicht automatisch, Luftgruppe dagegen Träger',()=>{let s=add(add(fresh(),'airbase'),'network');assert.throws(()=>add(s,'airwing'),/freie Plattform/);s=add(s,'carrier');assert.equal(totals(s.draft.units).build,336);s=add(s,'airwing');assert.throws(()=>add(s,'airwing'),/freie Plattform/);assert.throws(()=>removeUnit(s,s.draft.units.find(u=>u.type==='carrier').id),/abhängige/);});
test('Unbemannte Minenabwehr ist zusätzliche Ausstattung und benötigt beide Strukturen',()=>{let s=add(fresh(),'mine');assert.throws(()=>add(s,'unmannedMine'),/Datennetz/);s=add(add(s,'network'),'unmannedMine');assert.deepEqual(totals(s.draft.units),{build:22,operation:11,personnel:11});});
test('Überziehen bleibt im Entwurf möglich, Abgabe gesperrt',()=>{const s=ready(add(fresh(),'frigate',40));assert.ok(totals(s.draft.units).build>LIMITS.build);assert.throws(()=>submit(s),/überschritten/);assert.equal(s.submissions.length,0);});
test('Alle vier Begründungen und Gruppenname sind Pflicht',()=>{const s=add(fresh(),'corvette');assert.equal(submissionErrors(s.draft).length,5);assert.throws(()=>submit(s),/Namen/);assert.throws(()=>submit(ready(fresh())),/mindestens/);});
test('Abgaben sind getrennte Snapshots und durch Undo nicht Bestandteil des Entwurfs',()=>{let s=submit(ready(add(fresh(),'corvette')),'2026-09-20T12:00:00Z');const first=JSON.stringify(s.submissions[0]);assert.throws(()=>add(s,'frigate'),/abgegeben/);s=revise(s);s=add(s,'frigate');s.draft.rationale.tradeoffs='Geänderte Priorität';assert.equal(JSON.stringify(s.submissions[0]),first);s=submit(s,'2026-09-20T13:00:00Z');assert.equal(s.submissions.length,2);assert.equal(s.submissions[0].units.length,1);assert.equal(s.submissions[1].units.length,2);});
test('Datei-Rundreise erhält Entwurf, Zuordnungen und Abgaben',()=>{let s=add(add(add(fresh(),'dock'),'logistics'),'marines');s=submit(ready(s));s=revise(s);s=add(s,'corvette');assert.deepEqual(parseDocument(JSON.parse(JSON.stringify(s))),s);s=submit(s);assert.deepEqual(parseDocument(JSON.parse(JSON.stringify(s))),s);});
test('Import weist unbekannte Karten, doppelte Kennungen und kaputte Abgaben zurück',()=>{let s=add(fresh(),'corvette');let bad=copy(s);bad.draft.units[0].type='evil';assert.throws(()=>parseDocument(bad),/Ungültige Einheit/);bad=copy(s);bad.draft.units.push(copy(bad.draft.units[0]));assert.throws(()=>parseDocument(bad),/Doppelte/);bad=copy(s);bad.catalogVersion='future';assert.throws(()=>parseDocument(bad),/Version/);s=submit(ready(s));bad=copy(s);bad.draft.name='Verändert';assert.throws(()=>parseDocument(bad),/nachträglich/);bad=copy(s);bad.submissions[0].iteration=2;assert.throws(()=>parseDocument(bad),/Reihenfolge/);});
test('Import übernimmt keine zusätzlichen HTML-/Konfigurationsfelder',()=>{const s=add(fresh(),'corvette');s.draft.name='<img src=x onerror=alert(1)>';s.limits={build:9999};s.draft.units[0].cost={build:-100};const clean=parseDocument(s);assert.equal(clean.draft.name,s.draft.name);assert.equal(clean.limits,undefined);assert.equal(clean.draft.units[0].cost,undefined);});

test('Geerbte Objektnamen sind keine Karten',()=>{for(const type of ['__proto__','constructor','toString']){const s=add(fresh(),'corvette');s.draft.units[0].type=type;assert.throws(()=>parseDocument(s),/Ungültige Einheit/);assert.throws(()=>add(fresh(),type),/Unbekannte Karte/);}});
